### ISSUE TITLE
FontAwesome version 4

### ISSUE THREAD

**Issue by ds125v** [eduridden/moodle-filter_fontawesome#1]
A new version is out:

http://fontawesome.io/whats-new/?r=hn&v=4.0.0

With, most notably, a change in classnames (to follow Bootstrap 3 I think)

**Comment by DBezemer** [comment]
filed pull request: https://github.com/moodleman/moodle-filter_fontawesome/pull/2

**Comment by eduridden** [comment]
Sorry..should have closed this a while ago. Now updated
