### ISSUE TITLE
Issue with filter on demo site block

### ISSUE THREAD

**Issue by vaughany** [eduridden/moodle-filter_fontawesome#4]
Just seen this filter and love it! However, on the [demo site](http://features.demo.moodle.com.au/course/view.php?id=35), on the sample HTML block on the right, the filter doesn't appear to be working as I can see [icon-question-circle icon-5x], [icon-envelope], [icon-phone-square], and [icon-building].

Cheers,

Vaughany.

**Comment by eduridden** [comment]
Hi Vaughany,

You caught me mid upgrade. Visit the demo page again and it is all working.

Have just updated the filter and the new version of fontawesome now uses fa- instead of icon-

Julian

**Comment by vaughany** [comment]
I see, oops, sorry about that. :)
